import { Link } from "react-router-dom";
import { FileText, MapPin, Sparkles, Building2, Camera, BookOpen, ArrowRight } from "lucide-react";
import { useActiveProject } from "@/state/activeProject";

const sections = [
  { title: "Executive Summary", body: "Phase 0 readiness pulled from 12 jurisdictional sources + on-site capture.", Icon: BookOpen },
  { title: "Site Context", body: "Lot 0231 · 0.62 ac · zoned C-2-A · within historic overlay HD-MTV.", Icon: MapPin },
  { title: "Existing Structure", body: "1-story masonry, ~3,200 sf, built 1962 · vacant since 2019.", Icon: Building2 },
  { title: "Field Captures", body: "42 photos · 6 voice notes · GPS-anchored.", Icon: Camera },
];

const Sir = () => {
  const { active } = useActiveProject();
  return (
    <div className="space-y-6">
      <header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
        <div>
          <div className="pilot-kicker text-primary">Site Investigation Report</div>
          <h1 className="mt-2 font-display text-4xl font-semibold tracking-tight">{active.name}</h1>
          <p className="mt-1 text-sm text-muted-foreground">SIR · Rev 03 · auto-generated by Phase 0 agent stack</p>
        </div>
        <div className="flex gap-2">
          <Link to="/sir/workspace" className="pilot-button-ghost"><FileText className="h-4 w-4" /> Technical Workspace</Link>
          <Link to="/sir/executive" className="pilot-button-primary"><Sparkles className="h-4 w-4" /> View ESIR</Link>
        </div>
      </header>

      <section className="grid gap-4 md:grid-cols-2">
        {sections.map((s) => (
          <article key={s.title} className="pilot-card p-5">
            <div className="flex items-center gap-2">
              <s.Icon className="h-5 w-5 text-primary" />
              <h2 className="font-tight text-lg font-bold">{s.title}</h2>
            </div>
            <p className="mt-2 text-sm text-muted-foreground">{s.body}</p>
          </article>
        ))}
      </section>

      <section className="pilot-card p-5">
        <h3 className="font-tight text-lg font-bold">Annex Index</h3>
        <ul className="mt-3 divide-y divide-border">
          {[
            { label: "A · Technical Annex (codes, easements, utility maps)", to: "/sir/annex" },
            { label: "B · Sync Generator (SIR ↔ ESIR)", to: "/sir/sync" },
            { label: "C · Executive Brief", to: "/sir/executive" },
          ].map((r) => (
            <li key={r.to}>
              <Link to={r.to} className="flex items-center justify-between py-3 text-sm hover:text-primary">
                {r.label}
                <ArrowRight className="h-4 w-4" />
              </Link>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
};

export default Sir;