"use strict";

const { getValidAccessTokenForUser } = require("../microsoft/microsoft-graph-auth.service.js");
const { resolveAddressFromApplicationPackageSnapshot } = require("./uci-provider-setup.service.js");

const EMAIL_SUBMIT_VERSION = "d4-email-v1";

/**
 * @param {Record<string, unknown>} application
 * @param {Record<string, unknown>} project
 * @param {string} providerSlug
 */
function buildUtilitySubmissionEmailContent(application, project, providerSlug) {
  const address = resolveAddressFromApplicationPackageSnapshot(application, project);
  const packageMeta =
    application.agent_draft_metadata &&
    typeof application.agent_draft_metadata === "object" &&
    !Array.isArray(application.agent_draft_metadata)
      ? /** @type {{ application_package?: Record<string, unknown> }} */ (
          application.agent_draft_metadata
        ).application_package
      : null;

  const templateId =
    packageMeta && packageMeta.template_id != null ? String(packageMeta.template_id) : "unknown";
  const applicationType = String(application.application_type ?? "new_service");
  const provider = String(providerSlug || "utility").toUpperCase();

  const attachedDocs = Array.isArray(application.package_documents)
    ? /** @type {Array<Record<string, unknown>>} */ (application.package_documents).filter(
        (d) => String(d.status) === "attached",
      )
    : [];

  const attachmentLines = attachedDocs.map((d) => {
    const label = d.label != null ? String(d.label) : String(d.key ?? "document");
    const fileName = d.file_name != null ? String(d.file_name) : "attached file";
    return `- ${label}: ${fileName}`;
  });

  const subject = `[UCI] ${provider} ${applicationType} application — ${address.formatted || project.name || "project"}`;
  const body = [
    `Utility coordination application package for ${provider}.`,
    "",
    `Project: ${project.name ?? "Unknown"}`,
    `Address: ${address.formatted || "(not set)"}`,
    `Application type: ${applicationType}`,
    `Template: ${templateId}`,
    "",
    "Attached documents referenced in package:",
    attachmentLines.length ? attachmentLines.join("\n") : "(none attached in package)",
    "",
    "This message was generated by UCI Agent 4 email submission.",
    "Engineering load values are included only when verified in load_summary.calculated_values.",
  ].join("\n");

  return { subject, body, attachedDocs };
}

/**
 * @param {string} accessToken
 * @param {object} message
 * @param {string} message.subject
 * @param {string} message.body
 * @param {Array<{ file_name?: string, content_base64?: string, content_type?: string }>} [message.attachments]
 */
async function graphSendMail(accessToken, message) {
  const graphAttachments = (message.attachments || [])
    .filter((a) => a.content_base64)
    .map((a) => ({
      "@odata.type": "#microsoft.graph.fileAttachment",
      name: a.file_name || "attachment.pdf",
      contentType: a.content_type || "application/pdf",
      contentBytes: a.content_base64,
    }));

  const payload = {
    message: {
      subject: message.subject,
      body: {
        contentType: "Text",
        content: message.body,
      },
      attachments: graphAttachments.length ? graphAttachments : undefined,
    },
    saveToSentItems: true,
  };

  const r = await fetch("https://graph.microsoft.com/v1.0/me/sendMail", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!r.ok) {
    const text = await r.text();
    let detail = text.slice(0, 300);
    try {
      const parsed = JSON.parse(text);
      if (parsed?.error?.message) detail = String(parsed.error.message);
    } catch {
      /* ignore */
    }
    return { ok: false, status: r.status, error: detail };
  }

  return { ok: true, status: r.status, message_id: `graph-send-${Date.now()}` };
}

/**
 * @param {import("@supabase/supabase-js").SupabaseClient} supabase
 * @param {object} params
 * @param {Record<string, unknown>} params.application
 * @param {Record<string, unknown>} params.project
 * @param {string} params.userId
 * @param {string} params.providerSlug
 * @param {(accessToken: string, message: object) => Promise<{ ok: boolean, message_id?: string, error?: string }>} [params.sendMailFn]
 * @param {() => Promise<Array<{ file_name: string, content_base64: string, content_type?: string }>>} [params.resolveAttachmentsFn]
 * @param {() => Promise<string>} [params.getAccessTokenFn]
 */
async function sendUtilitySubmissionEmail(supabase, params) {
  const {
    application,
    project,
    userId,
    providerSlug,
    sendMailFn = graphSendMail,
    resolveAttachmentsFn,
    getAccessTokenFn,
  } = params;

  let accessToken = "";
  if (typeof getAccessTokenFn === "function") {
    try {
      accessToken = await getAccessTokenFn();
    } catch (err) {
      return {
        ok: false,
        code: "MAILBOX_NOT_CONNECTED",
        message: err instanceof Error ? err.message : "Mailbox unavailable",
        status: "human_required",
      };
    }
  } else {
    const tokenResult = await getValidAccessTokenForUser(supabase, userId).catch((err) => {
      const code =
        err && typeof err === "object" && "code" in err
          ? String(/** @type {{ code?: unknown }} */ (err).code)
          : "MAILBOX_NOT_CONNECTED";
      return { ok: false, code, message: err instanceof Error ? err.message : "Mailbox unavailable" };
    });

    if (
      typeof tokenResult === "object" &&
      tokenResult &&
      "ok" in tokenResult &&
      tokenResult.ok === false
    ) {
      return {
        ok: false,
        code: tokenResult.code || "MAILBOX_NOT_CONNECTED",
        message:
          tokenResult.message ||
          "Microsoft mailbox is not connected — connect mailbox in Settings before email submission",
        status: "human_required",
      };
    }

    accessToken = typeof tokenResult === "string" ? tokenResult : "";
  }

  if (!accessToken) {
    return {
      ok: false,
      code: "MAILBOX_NOT_CONNECTED",
      message: "Microsoft mailbox is not connected — connect mailbox in Settings before email submission",
      status: "human_required",
    };
  }

  const emailContent = buildUtilitySubmissionEmailContent(application, project, providerSlug);
  /** @type {Array<{ file_name: string, content_base64: string, content_type?: string }>} */
  let binaryAttachments = [];
  if (resolveAttachmentsFn) {
    try {
      binaryAttachments = await resolveAttachmentsFn();
    } catch (err) {
      return {
        ok: false,
        code: "ATTACHMENT_RESOLVE_FAILED",
        message: err instanceof Error ? err.message : "Failed to resolve email attachments",
        status: "failed",
      };
    }
  }

  const sendResult = await sendMailFn(accessToken, {
    subject: emailContent.subject,
    body: emailContent.body,
    attachments: binaryAttachments,
  });

  if (!sendResult.ok) {
    return {
      ok: false,
      code: "EMAIL_SEND_FAILED",
      message: sendResult.error || "Outbound email delivery failed",
      status: "failed",
      retryable: true,
    };
  }

  return {
    ok: true,
    status: "confirmed",
    version: EMAIL_SUBMIT_VERSION,
    message_id: sendResult.message_id ?? null,
    subject: emailContent.subject,
    attachment_count: binaryAttachments.length,
    referenced_documents: emailContent.attachedDocs.map((d) => ({
      key: d.key != null ? String(d.key) : null,
      file_name: d.file_name != null ? String(d.file_name) : null,
      project_document_id:
        d.project_document_id != null ? String(d.project_document_id) : null,
    })),
  };
}

module.exports = {
  EMAIL_SUBMIT_VERSION,
  buildUtilitySubmissionEmailContent,
  graphSendMail,
  sendUtilitySubmissionEmail,
};
